# Generated by Django 5.1 on 2024-12-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_project_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
