# Generated by Django 5.1 on 2025-01-02 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_projectmembership_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Progress percentage of the task (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
