# Generated by Django 5.1 on 2025-01-03 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_project_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INVITATION', 'Invitation'), ('UPDATE', 'Update')], default='UPDATE', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='my_app.project'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='my_app.task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(blank=True, default='/static/profile_pictures/default_profile.jpg', max_length=255, null=True),
        ),
    ]
